import { useEffect, useCallback } from 'react';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import usePlannerStore from '../../store/plannerStore';
import toast from 'react-hot-toast';

// PDF Styles
const s = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#0F172A' },
  header: { marginBottom: 20, borderBottomWidth: 2, borderBottomColor: '#4F46E5', paddingBottom: 15 },
  logo: { fontSize: 24, fontFamily: 'Helvetica-Bold', color: '#4F46E5', marginBottom: 4 },
  tagline: { fontSize: 10, color: '#64748B' },
  title: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 10, color: '#0F172A' },
  subtitle: { fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 8, marginTop: 16, color: '#4F46E5' },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  label: { color: '#64748B', fontSize: 10 },
  value: { fontFamily: 'Helvetica-Bold', fontSize: 10 },
  divider: { borderBottomWidth: 1, borderBottomColor: '#E2E8F0', marginVertical: 8 },
  card: { backgroundColor: '#F8FAFC', borderRadius: 6, padding: 12, marginBottom: 8 },
  dayHeader: { fontSize: 12, fontFamily: 'Helvetica-Bold', marginBottom: 6, color: '#0F172A' },
  shiftLabel: { fontSize: 9, color: '#4F46E5', fontFamily: 'Helvetica-Bold', marginBottom: 2, textTransform: 'uppercase' },
  shiftValue: { fontSize: 10, color: '#334155', marginBottom: 6 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#94A3B8' },
  badge: { backgroundColor: '#4F46E5', borderRadius: 4, paddingHorizontal: 8, paddingVertical: 3, color: 'white', fontSize: 9, fontFamily: 'Helvetica-Bold', alignSelf: 'flex-start', marginBottom: 6 },
  tcItem: { fontSize: 8, color: '#64748B', marginBottom: 3 },
});

function TourPdf({ data }) {
  const { countryName, totalDays, totalNights, travelType, startDate, templateName,
    itinerary, inclusions, exclusions } = data;

  // Day tour total
  const dayTourTotal = itinerary.reduce((sum, day) => {
    const price = day.dayTour?.price ? Number(day.dayTour.price) : 0;
    return sum + price;
  }, 0);

  return (
    <Document>
      {/* Page 1: Overview + Itinerary */}
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <Text style={s.logo}>DigiWave</Text>
          <Text style={s.tagline}>Tour Planning | Personalized Itinerary</Text>
        </View>

        <Text style={s.title}>{countryName} Tour Plan</Text>

        {/* Trip Summary */}
        <View style={s.card}>
          <View style={s.row}><Text style={s.label}>Destination</Text><Text style={s.value}>{countryName}</Text></View>
          <View style={s.row}><Text style={s.label}>Duration</Text><Text style={s.value}>{totalDays} Days / {totalNights} Nights</Text></View>
          <View style={s.row}><Text style={s.label}>Travel Type</Text><Text style={s.value}>{travelType || 'N/A'}</Text></View>
          {templateName && <View style={s.row}><Text style={s.label}>Template</Text><Text style={s.value}>{templateName}</Text></View>}
          {startDate && <View style={s.row}><Text style={s.label}>Start Date</Text><Text style={s.value}>{startDate}</Text></View>}
        </View>

        {/* Day-by-day */}
        <Text style={s.subtitle}>Day-by-Day Itinerary</Text>
        {itinerary.map((day) => (
          <View key={day.dayNumber} style={s.card} wrap={false}>
            <Text style={s.dayHeader}>
              Day {day.dayNumber}{day.isArrival ? ' — Arrival' : ''}{day.isDeparture ? ' — Departure' : ''}
            </Text>
            {day.date && <Text style={{ ...s.label, marginBottom: 4 }}>{day.date}</Text>}
            {day.dayTour?.activity_combination && (
              <View><Text style={s.shiftLabel}>Activities</Text><Text style={s.shiftValue}>{day.dayTour.activity_combination}</Text></View>
            )}
            {day.dayTour?.itinerary_text && (
              <Text style={{ ...s.label, marginBottom: 4 }}>{day.dayTour.itinerary_text}</Text>
            )}
            {day.dayTour?.attractions?.length > 0 && (
              <Text style={{ ...s.label, marginBottom: 4 }}>
                Sights: {day.dayTour.attractions.sort((a, b) => a.visit_order - b.visit_order).map(a => a.attraction_name).join(' → ')}
              </Text>
            )}
            {day.dayTour?.overnight_location && (
              <Text style={{ ...s.label, marginBottom: 2 }}>Overnight: {day.dayTour.overnight_location}</Text>
            )}
            {day.dayTour?.price && Number(day.dayTour.price) > 0 && (
              <Text style={{ ...s.value, color: '#4F46E5', marginTop: 2 }}>{day.dayTour.currency || 'INR'} {Number(day.dayTour.price).toLocaleString()}</Text>
            )}
          </View>
        ))}

        <Text style={s.footer}>Generated by DigiWave Tour Planner | Confidential</Text>
      </Page>

      {/* Page 2: Inclusions + Exclusions + T&C */}
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <Text style={s.logo}>DigiWave</Text>
          <Text style={s.tagline}>Inclusions, Exclusions & Terms</Text>
        </View>

        {/* Estimated Cost */}
        {dayTourTotal > 0 && (
          <>
            <Text style={s.title}>Estimated Cost</Text>
            <View style={s.card}>
              {itinerary.filter(d => d.dayTour?.price && Number(d.dayTour.price) > 0).map(d => (
                <View key={d.dayNumber} style={s.row}>
                  <Text style={s.label}>Day {d.dayNumber} — {d.dayTour?.activity_combination || 'Tour'}</Text>
                  <Text style={s.value}>{d.dayTour.currency || 'INR'} {Number(d.dayTour.price).toLocaleString()}</Text>
                </View>
              ))}
              <View style={s.divider} />
              <View style={s.row}>
                <Text style={{ ...s.value, fontSize: 12 }}>Estimated Total</Text>
                <Text style={{ ...s.value, fontSize: 12, color: '#4F46E5' }}>INR {dayTourTotal.toLocaleString()}</Text>
              </View>
            </View>
          </>
        )}

        {/* Inclusions */}
        <Text style={s.subtitle}>Inclusions</Text>
        <View style={s.card}>
          {inclusions.length === 0 && <Text style={s.label}>No inclusions selected</Text>}
          {inclusions.map(item => (
            <Text key={item.id} style={{ ...s.label, marginBottom: 3 }}>✓ {item.service}</Text>
          ))}
        </View>

        {/* Exclusions */}
        <Text style={s.subtitle}>Exclusions</Text>
        <View style={s.card}>
          {exclusions.length === 0 && <Text style={s.label}>No exclusions noted</Text>}
          {exclusions.map(item => (
            <Text key={item.id} style={{ ...s.label, marginBottom: 3 }}>✗ {item.service}</Text>
          ))}
        </View>

        {/* Terms */}
        <Text style={s.subtitle}>Terms & Conditions</Text>
        <View style={s.card}>
          {[
            'This quotation is valid for 7 days from the date of generation.',
            'Prices are subject to availability at the time of booking.',
            '50% advance payment required to confirm the booking.',
            'Cancellation charges apply as per the cancellation policy.',
            'Force majeure events are not covered under this quotation.',
            'Exchange rate fluctuations may affect the final pricing.',
            'Any deviation in itinerary may lead to revised pricing.',
          ].map((tc, i) => (
            <Text key={i} style={s.tcItem}>{i + 1}. {tc}</Text>
          ))}
        </View>

        <Text style={s.footer}>Generated by DigiWave Tour Planner | Confidential | Page 2</Text>
      </Page>
    </Document>
  );
}

export default function PdfGenerator() {
  const store = usePlannerStore();

  const generateAndDownload = useCallback(async () => {
    try {
      // Build inclusion/exclusion lists from store
      const inclusions = [];
      const exclusions = [];
      if (store.inclusionsData) {
        for (const [type, groups] of Object.entries(store.inclusionsData)) {
          for (const items of Object.values(groups)) {
            for (const item of items) {
              if (store.selectedInclusions.includes(item.id)) {
                if (type === 'INCLUSION') inclusions.push(item);
                else exclusions.push(item);
              }
            }
          }
        }
      }

      const data = {
        countryName: store.selectedCountry?.name || 'Tour',
        totalDays: store.totalDays,
        totalNights: store.totalNights,
        travelType: store.travelType,
        startDate: store.startDate,
        templateName: store.selectedTemplate?.name,
        itinerary: store.itinerary,
        inclusions,
        exclusions,
      };

      const blob = await pdf(<TourPdf data={data} />).toBlob();
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `DigiWave_Tour_${store.selectedCountry?.name || 'Plan'}_${new Date().toISOString().split('T')[0]}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      toast.success('PDF downloaded successfully!');
    } catch (err) {
      console.error('PDF generation failed:', err);
      toast.error('PDF generation failed. Please try again.');
    }
  }, [store]);

  useEffect(() => {
    const handler = () => generateAndDownload();
    window.addEventListener('download-pdf', handler);
    return () => window.removeEventListener('download-pdf', handler);
  }, [generateAndDownload]);

  // This component renders nothing - it just listens for download events
  return null;
}
